using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public class RocketControl : MonoBehaviour
{
    [SerializeField] private GameManager gameManager = null!;
    [SerializeField] private float GravityCoefficient;//ï¿½ï¿½ï¿½Lï¿½ï¿½ï¿½Í’è”
    [SerializeField] private float startDash;//ï¿½ï¿½ï¿½ï¿½ï¿½x
    [SerializeField] private float escapeTime;//ï¿½ï¿½ï¿½Eï¿½ï¿½ï¿½ï¿½ï¿½Ü‚Å‚Ìï¿½ï¿½ï¿½
    [SerializeField] private float maxCharge;//chargeï¿½ÌÅ‘ï¿½l
    [SerializeField] private float charge;//chargeï¿½Ì’l
    [SerializeField] private float chargeSpeed;//chargeï¿½Ì‘ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½x
    [SerializeField] private float exprosionCharge;//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ç”šï¿½jï¿½ï¿½ï¿½ï¿½charge
    [SerializeField] private float fuel;//ï¿½ï¿½ï¿½Ú“ï¿½ï¿½Åï¿½ï¿½ï‚·ï¿½ï¿½l
    [SerializeField] private float maxFuel;//ï¿½ï¿½ï¿½Ú“ï¿½ï¿½ñ”‚ÌÅ‘ï¿½l
    [SerializeField] private float fuelRecovery;
    [SerializeField] private float spCooltime;//spï¿½ï¿½ï¿½ï¿½(ï¿½ï¿½ï¿½Ú“ï¿½)ï¿½ÌƒNï¿½[ï¿½ï¿½ï¿½^ï¿½Cï¿½ï¿½
    [SerializeField] private float spHorizonSpeed;//ï¿½ï¿½ï¿½Ú“ï¿½ï¿½ï¿½ï¿½x
    [SerializeField] private float spConsumeFuel;//ï¿½ï¿½ï¿½Ú“ï¿½ï¿½ï¿½ï¿½xï¿½Å‚Ì”Rï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    [SerializeField] private float horizonSpeed;//ï¿½ï¿½ï¿½Ú“ï¿½ï¿½ï¿½ï¿½x
    [SerializeField] private float breakSpeed;//ï¿½ï¿½ï¿½Ú“ï¿½ï¿½ï¿½ï¿½x
    [SerializeField] private float spAccelSpeed;
    [SerializeField] private float maxAngleZ;
    [SerializeField] private float spMaxAngleZ;
    [SerializeField] private float rotationSpeedZ;
    [SerializeField] private float antiRotationSpeedZ;
    [SerializeField] private GameObject explosionPrefab;
    [SerializeField] private ParticleSystem rightParticle;
    [SerializeField] private ParticleSystem leftParticle;
    [SerializeField] private ParticleSystem frontParticle;
    [SerializeField] private MainCamera mainCameraCon;
    public bool autoCamera;
    public bool crash { get; private set; } = false;
    public bool inOrbit = false; // ï¿½Oï¿½ï¿½ï¿½Éï¿½ï¿½ï¿½Ä‚é‚©ï¿½Ì”ï¿½ï¿½ï¿½
    public bool leftAround = false; // ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½
    public bool rightAround = false; // ï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½
    public bool escape = false; // ï¿½Oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì—ï¿½ï¿½Eï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    public Vector3 PlanetPos; // ï¿½fï¿½ï¿½ï¿½ÌˆÊ’u
    public Vector3 delta; // ï¿½ï¿½ï¿½Pï¿½bï¿½gï¿½Ì‘ï¿½ï¿½xï¿½xï¿½Nï¿½gï¿½ï¿½
    private Vector3 saveVelocity; // ï¿½ï¿½ï¿½xï¿½xï¿½Nï¿½gï¿½ï¿½ï¿½Ì•Û‘ï¿½
    public Vector3 nowPosition { get; private set; } // ï¿½ï¿½ï¿½Ìƒï¿½ï¿½Pï¿½bï¿½gï¿½ÌˆÊ’u
    public float compleatEscapeTime { get; private set; }
    public GameObject orbitCenter;
    private List<GameObject> colList = new List<GameObject>();
    private Rigidbody rb;
    private Transform myTransform;
    private GameObject mainCamera;
    private GameObject subCamera;
    private GameObject ds;
    private Planet planet;
    private bool start = false; // ï¿½Xï¿½^ï¿½[ï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì”ï¿½ï¿½ï¿½
    private bool emergencyAvoidance = false;//ï¿½ï¿½ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    private bool spCooldown = false;//spï¿½ï¿½ï¿½ï¿½ÌƒNï¿½[ï¿½ï¿½ï¿½_ï¿½Eï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    private bool spAngleCount = false;
    private Vector3 prePosition; // 1ï¿½tï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½Oï¿½Ìƒï¿½ï¿½Pï¿½bï¿½gï¿½ÌˆÊ’u
    private float orbitalRadius;
    private float escapeOrbitalRadius;// ï¿½Oï¿½ï¿½ï¿½ï¿½ï¿½a
    private float mass = 1; // ï¿½fï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½
    private float speed; // ï¿½ï¿½ï¿½Pï¿½bï¿½gï¿½Ì‘ï¿½ï¿½ï¿½
    private Vector3 relativeRocketPos;
    private float rotateSpeed;
    public float chargePower { get; private set; }
    private float angleChangeTime;
    public float rotationZ { get; private set; }
    private float carrentRotationZ;
    private float spAngleChangeTime;
    private float spAngleChangeRatio;
    private float spAngleZ;
    private float horizonInput;

    private float resultMaxSpeed = 0;//æœ€é«˜é€Ÿåº¦
    private float resultTime; //çµŒéæ™‚é–“
    private int resultPlanetCount;//è¨ªã‚ŒãŸæ˜Ÿã®æ•°
    private int resultSpCount;//ç·Šæ€¥å›é¿ã—ãŸå›æ•°
    public int resultCauseOfDeath;//æ­»å› 

    public bool InGravity()
    {
        return colList.Any();
    }
    public void RemovePlanetFromColList(GameObject obj)
    {
        colList.Remove(obj);
        Debug.Log("called Remove Planet From ColList");
    }
    public float FuelAmount()
    {
        return fuel;
    }

    // Start is called before the first frame update
    private void Start()
    {
        ds = GameObject.Find("DirectionSign");
        mainCamera = GameObject.Find("Main Camera");
        subCamera = GameObject.Find("Sub Camera");      
        rb = GetComponent<Rigidbody>();
        myTransform = transform;
    }    
    
    //ï¿½ï¿½ï¿½xï¿½xï¿½Nï¿½gï¿½ï¿½(delta)ï¿½Ìæ“¾
    private void GetDeltaPos()
    {
        nowPosition = myTransform.position;
        delta = (nowPosition - prePosition) / Time.deltaTime;
        prePosition = nowPosition;
        if (start)
        { 
            resultMaxSpeed = System.Math.Max(resultMaxSpeed, delta.magnitude); 
        }
    }
    //ï¿½Oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Eï¿½oï¿½ï¿½ï¿½ï¿½
    void CompleatEscape()
    {
        //Debug.Log("CompleatEscape");
        escape = false;
    }

    public void RocketDestroy()
    {
        gameManager.StartGameFinish(resultCauseOfDeath, resultTime, resultMaxSpeed, resultPlanetCount, resultSpCount);
        crash = true;
        mainCamera.SetActive(true);
        subCamera.SetActive(false);
        Instantiate(explosionPrefab, this.transform.position, Quaternion.identity);
        Destroy(mainCameraCon);
        this.gameObject.transform.DetachChildren();
        Destroy(ds);
        Destroy(this.gameObject);
        Destroy(this);
    }

    public void RocketUpdate()
    {
        if(Input.GetKey(KeyCode.Return))
        {
            resultCauseOfDeath = 6;
            RocketDestroy();
        }
        autoCamera = Setting.autoCamera;
        GetComponent<TrailRenderer>().enabled = Setting.rocketTrajectoryExist;
        GetDeltaPos();
        if (start == false)//ï¿½Xï¿½^ï¿½[ï¿½gï¿½_ï¿½bï¿½Vï¿½ï¿½
        {
            angleChangeTime = 0;
            if (Input.GetKey(KeyCode.Space))
            {
                Vector3 StartDirection = new Vector3(0f, 0f, startDash);
                rb.AddForce(StartDirection);
                start = true;
            }
        }

        if(start)//ï¿½Xï¿½^ï¿½[ï¿½gï¿½ï¿½fuleï¿½Ìï¿½ï¿½Ô“ï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½
        {
            fuel -= Time.deltaTime;
            resultTime += Time.deltaTime;
        }
        if(fuel <= 0)
        {
            //Debug.Log("Finish!");
            resultCauseOfDeath = 1;//æ­»å› ï¼šç‡ƒæ–™ãŒãªããªã£ãŸã€‚
            RocketDestroy();
        }
        fuel = Mathf.Clamp(fuel, 0, maxFuel);//fuelï¿½ÌÅï¿½ï¿½lï¿½Å‘ï¿½lï¿½ï¿½ï¿½ï¿½

        spAngleChangeTime += Time.deltaTime;
        spAngleChangeRatio = spAngleChangeTime / 0.2f;
        spAngleChangeRatio = Mathf.Clamp(spAngleChangeRatio, 0, 1);
        if(emergencyAvoidance)
        {
            
            if(spAngleCount)
            {
                rotationZ = Mathf.Lerp(carrentRotationZ, spAngleZ, spAngleChangeRatio);
                if (spAngleChangeRatio >= 1)
                {
                    spAngleCount = false;
                    spAngleChangeTime = 0;
                }
            }
            else
            {
                rotationZ = Mathf.Lerp(spAngleZ, 0, spAngleChangeRatio);
            }
            myTransform.rotation = Quaternion.Euler(0, myTransform.localEulerAngles.y, rotationZ);
            
        }
        else
        {
            rotationZ = maxAngleZ * angleChangeTime;//ãƒ­ã‚±ãƒƒãƒˆã®å‚¾ã
            var rocketAngle = Vector3.Angle(delta, Vector3.forward);
            var rocketAxis = Vector3.Cross(delta, Vector3.forward).y < 0 ? -1 : 1;
            var normalizedAngle = Mathf.Repeat(-rocketAngle * rocketAxis, 360);
            myTransform.rotation = Quaternion.Euler(0, normalizedAngle, rotationZ);
            //Debug.Log(normalizedAngle);
        }
        if (Input.GetKey(KeyCode.RightArrow) || Input.GetKey(KeyCode.D))
        {
            horizonInput = 1;
        }
        else if(Input.GetKey(KeyCode.LeftArrow) || Input.GetKey(KeyCode.A))
        {
            horizonInput = -1;
        }
        else
        {
            horizonInput = 0;
        }

        Vector3 forward = myTransform.forward;//ï¿½ï¿½ï¿½Ê•ï¿½ï¿½ï¿½ï¿½Ìƒxï¿½Nï¿½gï¿½ï¿½
        Vector3 moveDirection = delta.normalized; //ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì’Pï¿½Êƒxï¿½Nï¿½gï¿½ï¿½
        if (!inOrbit && start)//ï¿½Oï¿½ï¿½ï¿½ÌŠOï¿½Å‚Ì‘ï¿½ï¿½ï¿½
        {
            Vector3 horizon = Quaternion.Euler(0, 90, 0) * moveDirection;//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ìƒxï¿½Nï¿½gï¿½ï¿½
            if (KeyManager.space.keep && fuel > spConsumeFuel && !spCooldown)
            {
                if (!(horizonInput == 0))//ï¿½ï¿½ï¿½Ú“ï¿½ç·Šæ€¥å›é¿ä½œå‹•
                {
                    gameManager.RocketMoveAudio();
                    resultSpCount += 1;
                    ParticleSystem particle = horizonInput > 0 ? rightParticle : leftParticle;
                    particle.Play();
                    Vector3 horizonMove = horizonInput * horizon * spHorizonSpeed;
                    fuel -= spConsumeFuel;//fuelï¿½ï¿½10ï¿½ï¿½ï¿½ï¿½
                    carrentRotationZ = rotationZ;
                    spAngleZ = -spMaxAngleZ * horizonInput;
                    emergencyAvoidance = true;                                       
                    spCooldown = true;//spï¿½Nï¿½[ï¿½ï¿½ï¿½_ï¿½Eï¿½ï¿½on
                    spAngleCount = true;
                    angleChangeTime = 0;
                    spAngleChangeTime = 0;
                    rb.velocity += horizonMove;//ï¿½ï¿½ï¿½Ú“ï¿½ï¿½Ìï¿½ï¿½s
                    Invoke("cooldown", spCooltime);                   
                    StartCoroutine("antiHorizon", horizonMove);//ï¿½ï¿½ï¿½Ú“ï¿½ï¿½ï¿½~ï¿½ÌŒÄ‚Ñoï¿½ï¿½
                }
                if (KeyManager.vertical.keep && KeyManager.vertical.axis > 0)
                {
                    gameManager.RocketMoveAudio();
                    frontParticle.Play();
                    Vector3 accelMove = moveDirection * spAccelSpeed;
                    fuel -= spConsumeFuel;//fuelï¿½ï¿½10ï¿½ï¿½ï¿½ï¿½
                    spCooldown = true;//spï¿½Nï¿½[ï¿½ï¿½ï¿½_ï¿½Eï¿½ï¿½on
                    rb.velocity += accelMove;//ï¿½ï¿½ï¿½Ú“ï¿½ï¿½Ìï¿½ï¿½s
                    Invoke("cooldown", spCooltime);
                }
            }
            else if(!emergencyAvoidance)
            {
                if (KeyManager.horizontal.keep)//æ¨ªç§»å‹•
                {
                    float rocketAngle = Vector3.Angle(moveDirection, myTransform.position);
                    float rocketAxis = Vector3.Cross(moveDirection, myTransform.position).y < 0 ? -1 : 1;
                    float angle = rocketAngle * rocketAxis;
                    Vector3 horizonSize = horizon * horizonSpeed;
                    angleChangeTime = Mathf.Clamp(angleChangeTime, -1, 1);
                    if(angle < 90 && KeyManager.horizontal.axis < 0)//å·¦
                    {
                        rb.AddForce(-horizonSize);
                        if(angleChangeTime >= 0)
                        {
                            angleChangeTime += rotationSpeedZ;
                        }
                        if (angleChangeTime < 0)
                        {
                            angleChangeTime += antiRotationSpeedZ;
                        }

                    }
                    if (angle > -90 && KeyManager.horizontal.axis > 0)//å³
                    {
                        rb.AddForce(horizonSize);
                        if (angleChangeTime <= 0)
                        {
                            angleChangeTime -= rotationSpeedZ;
                        }
                        if (angleChangeTime > 0)
                        {
                            angleChangeTime -= antiRotationSpeedZ;
                        }
                    }
                }
                else//æ¨ªç§»å‹•ã—ã¦ã„ãªã„ã¨ãè§’åº¦ã‚’å…ƒã«æˆ»ã™
                {
                    if(angleChangeTime < 0)
                    {
                        angleChangeTime += antiRotationSpeedZ;
                        angleChangeTime = System.Math.Min(angleChangeTime, 0);    
                    }
                    if(angleChangeTime > 0)
                    {
                        angleChangeTime -= antiRotationSpeedZ;
                        angleChangeTime = System.Math.Max(angleChangeTime, 0);
                    }
                }

                if (KeyManager.vertical.axis < 0 && rb.velocity.magnitude > 100f)//ãƒ–ãƒ¬ãƒ¼ã‚­
                {
                    rb.AddForce(-moveDirection * breakSpeed);
                }
            }
        }

        if (inOrbit)//ï¿½Oï¿½ï¿½ï¿½Ì’ï¿½ï¿½Å‚Ì‘ï¿½ï¿½ï¿½
        {
            Debug.Log("inOrbit");
            if (angleChangeTime < 0)//è§’åº¦Zã‚’0ã«æˆ»ã™
            {
                angleChangeTime += antiRotationSpeedZ;
                angleChangeTime = System.Math.Min(angleChangeTime, 0);
            }
            if (angleChangeTime > 0)
            {
                angleChangeTime -= antiRotationSpeedZ;
                angleChangeTime = System.Math.Max(angleChangeTime, 0);
            }

            chargePower = System.Math.Min(charge, 1);//chargeï¿½ÌÅ‘ï¿½lï¿½ï¿½ï¿½ï¿½
            float escapeSpeed = saveVelocity.magnitude;//ï¿½Oï¿½ï¿½ï¿½ï¿½ï¿½Eï¿½ï¿½ï¿½Ì‘ï¿½ï¿½ï¿½
            if (KeyManager.space.keep)
            {
                Debug.Log("charge");
                charge += chargeSpeed;//ï¿½Xï¿½yï¿½[ï¿½Xï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½chargeï¿½ğ‘‰ï¿½
            }
            else if (chargePower > 0)//ï¿½Xï¿½yï¿½[ï¿½Xï¿½Lï¿½[ï¿½ğ—£‚ï¿½ï¿½ï¿½ï¿½Æ‚ï¿½
            {
                Debug.Log("Escape");
                if (autoCamera)
                {
                    mainCamera.SetActive(true);
                    subCamera.SetActive(false);
                }
                gameManager.RocketMoveAudio();
                frontParticle.Play();
                rb.velocity = forward * (escapeSpeed + (maxCharge * chargePower));//ï¿½ï¿½ï¿½Ê•ï¿½ï¿½ï¿½ï¿½É‘ï¿½ï¿½xï¿½ï¿½^ï¿½ï¿½ï¿½ï¿½           
                charge = 0f;//chargeï¿½Ìƒï¿½ï¿½Zï¿½bï¿½g
                escape = true;//escapeï¿½ï¿½ï¿½ï¿½ï¿½ï¿½on
                compleatEscapeTime = Mathf.Pow((Mathf.Pow(escapeOrbitalRadius, 2) - Mathf.Pow(relativeRocketPos.magnitude, 2)), 0.5f) / escapeSpeed + escapeTime;
                Invoke("CompleatEscape",compleatEscapeTime);//escapeï¿½ï¿½ï¿½ï¿½ï¿½ÌŒÄ‚Ñoï¿½ï¿½
            }
            if(charge > exprosionCharge)//chargeï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ‚ï¿½ï¿½ï¿½ï¿½j
            {
                //Debug.Log("Explosion!");//ï¿½ï¿½
                resultCauseOfDeath = 3;//æ­»å› ï¼šåŠ›ã‚’è²¯ã‚ã™ããŸã€‚
                RocketDestroy();
            }
        }
        //Debug.Log(speedVector.magnitude);
        //ï¿½Oï¿½ï¿½ï¿½Éï¿½ï¿½ï¿½Ä‚é‚©ï¿½ï¿½ï¿½ï¿½
        if(leftAround == true || rightAround == true)
        {
            inOrbit = true;
        }
        else
        {
            inOrbit = false;
        }

        if(escape == true)//ï¿½Oï¿½ï¿½ï¿½ï¿½ï¿½Eï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        {
            leftAround = false;
            rightAround = false;
        }
    }

    private void OnCollisionEnter(Collision collision) //ï¿½Ô‚Â‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ‚ï¿½
    {
        //Debug.Log("CrashExprosion!");//ï¿½ï¿½
        resultCauseOfDeath = 2;//æ­»å› ï¼šæ˜Ÿã«è¡çªã—ãŸã€‚
        RocketDestroy();
    }

    private void OnTriggerEnter(Collider collider) //ï¿½dï¿½ÍŒï¿½ï¿½É“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ‚ï¿½
    {
        //ï¿½ß‚Ã‚ï¿½ï¿½ï¿½ï¿½fï¿½ï¿½ï¿½Ìï¿½ï¿½Ìæ“¾
        if (collider.gameObject.tag == "Planet" && !colList.Contains(collider.gameObject))
        {
            colList.Add(collider.gameObject);
        }
        if(collider.gameObject.tag == "BlackHole")
        {
            resultCauseOfDeath = 5;
            gameManager.StartGameFinish(resultCauseOfDeath, resultTime, resultMaxSpeed, resultPlanetCount, resultSpCount);
            crash = true;
            mainCamera.SetActive(true);
            subCamera.SetActive(false);
            this.gameObject.transform.DetachChildren();
            Destroy(ds);
            Destroy(this.gameObject);
            Destroy(this);
        }
    }
    void OnTriggerExit(Collider collider)
    {
        if (collider.gameObject.tag == "Planet" && colList.Contains(collider.gameObject))
        {
            colList.Remove(collider.gameObject);
        }
    }

    private void OnTriggerStay(Collider collider) //ï¿½dï¿½ÍŒï¿½ï¿½É‚ï¿½ï¿½ï¿½Æ‚ï¿½
    {
        if (!escape && !emergencyAvoidance)//ï¿½Oï¿½ï¿½ï¿½ï¿½ï¿½Eï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        {
            if (collider.gameObject.tag == "Planet")
            {
                foreach (GameObject planetObject in colList)
                {
                    planet = planetObject.GetComponent<Planet>();
                    mass = planet.mass;
                    orbitalRadius = planet.planetRadius * 2;
                    //Debug.Log(colList.Count);
                    //ï¿½dï¿½ï¿½
                    //ï¿½ß‚Ã‚ï¿½ï¿½ï¿½ï¿½fï¿½ï¿½ï¿½Ìï¿½ï¿½Wï¿½Ìæ“¾
                    PlanetPos = planetObject.transform.position;
                    //ï¿½ï¿½ï¿½Pï¿½bï¿½gï¿½ï¿½ï¿½ï¿½fï¿½ï¿½ï¿½Ì’ï¿½ï¿½Sï¿½ÖŒï¿½ï¿½ï¿½ï¿½ï¿½ï¿½xï¿½Nï¿½gï¿½ï¿½ï¿½Ìæ“¾
                    Vector3 gravityDirection = PlanetPos - myTransform.position;
                    //ï¿½ï¿½ï¿½Pï¿½bï¿½gï¿½Æ˜fï¿½ï¿½ï¿½Ì‹ï¿½ï¿½ï¿½ï¿½Ìæ“¾
                    float GravityLength = gravityDirection.magnitude;
                    //Debug.Log(GravityLength);
                    //ï¿½Pï¿½Êƒxï¿½Nï¿½gï¿½ï¿½ï¿½Ìæ“¾
                    Vector3 GravityNlz = gravityDirection.normalized;
                    //ï¿½dï¿½Í‚ÌŒvï¿½Z
                    Vector3 GravityForth = GravityNlz * GravityCoefficient * mass / Mathf.Pow(GravityLength, 2);

                    if (GravityLength < orbitalRadius)
                    {
                        //ï¿½ï¿½ï¿½ï¿½Ìê‡
                        Debug.Log("Inside");
                        //Debug.Log(planet.name);
                        //ï¿½ï¿½ï¿½xï¿½xï¿½Nï¿½gï¿½ï¿½ï¿½Æ˜fï¿½ï¿½ï¿½ÉŒï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ìƒxï¿½Nï¿½gï¿½ï¿½ï¿½Ì‚È‚ï¿½ï¿½p                
                        var axis = Vector3.Cross(gravityDirection, delta).y < 0 ? -1 : 1;//ï¿½Oï¿½ÏŒvï¿½Z(ï¿½È‚ï¿½ï¿½pï¿½ï¿½-180ï¿½ï¿½ï¿½ï¿½180ï¿½É‚ï¿½ï¿½ï¿½Ì‚É•Kï¿½v)
                        var angle = Vector3.Angle(gravityDirection, delta) * (axis);//ï¿½È‚ï¿½ï¿½p
                                                                                    //ï¿½È‚ï¿½ï¿½pï¿½ï¿½_ï¿½E0ï¿½ï¿½ï¿½ï¿½180_ï¿½ï¿½0ï¿½ï¿½ï¿½ï¿½-180                          
                                                                                    //Debug.Log(angle);

                        if (angle > 85 && !leftAround && !rightAround) //ï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½
                        {
                            escapeOrbitalRadius = orbitalRadius;
                            relativeRocketPos = -gravityDirection;//ï¿½Oï¿½ï¿½ï¿½Ì”ï¿½ï¿½aï¿½Æ‚È‚ï¿½xï¿½Nï¿½gï¿½ï¿½ï¿½Ìæ“¾
                            speed = delta.magnitude;//ï¿½ï¿½ï¿½ï¿½ï¿½ÌŒvï¿½Z
                            saveVelocity = rb.velocity;//ï¿½ï¿½ï¿½xï¿½Ì•Û‘ï¿½
                            rb.velocity = Vector3.zero;//Rigidbodyï¿½Ì‹@ï¿½\ï¿½ï¿½~
                            rightAround = true;//ï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½è”»ï¿½ï¿½ON
                            orbitCenter = planetObject;
                            fuel += fuelRecovery;
                            resultPlanetCount += 1;
                            if (autoCamera)
                            {
                                mainCamera.SetActive(false);
                                subCamera.SetActive(true);
                            }
                        }

                        if (angle < -85 && !leftAround && !rightAround) //ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½
                        {
                            escapeOrbitalRadius = orbitalRadius;
                            relativeRocketPos = -gravityDirection;//ï¿½Oï¿½ï¿½ï¿½Ì”ï¿½ï¿½aï¿½Æ‚È‚ï¿½xï¿½Nï¿½gï¿½ï¿½ï¿½Ìæ“¾
                            speed = delta.magnitude;//ï¿½ï¿½ï¿½ï¿½ï¿½ÌŒvï¿½Z
                            saveVelocity = rb.velocity;//ï¿½ï¿½ï¿½xï¿½Ì•Û‘ï¿½
                            rb.velocity = Vector3.zero;//Rigidbodyï¿½Ì‹@ï¿½\ï¿½ï¿½~
                            leftAround = true;//ï¿½ï¿½ï¿½vï¿½ï¿½è”»ï¿½ï¿½ON
                            orbitCenter = planetObject;
                            fuel += fuelRecovery;
                            resultPlanetCount += 1;
                            if (autoCamera)
                            {
                                mainCamera.SetActive(false);
                                subCamera.SetActive(true);
                            }
                        }
                    }

                    if (rightAround)//ï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½ï¿½ï¿½s
                    {
                        rotateSpeed = Mathf.Rad2Deg * ((speed + (maxCharge * chargePower)) / relativeRocketPos.magnitude);//ï¿½pï¿½ï¿½ï¿½xï¿½ÌŒvï¿½Z
                        relativeRocketPos = Quaternion.Euler(0, -rotateSpeed * Time.deltaTime / Mathf.Pow(colList.Count, 2), 0) * relativeRocketPos;//ï¿½xï¿½Nï¿½gï¿½ï¿½ï¿½Ì‰ï¿½]
                        Vector3 rocketPos = relativeRocketPos + orbitCenter.transform.position;//ï¿½ï¿½ï¿½Pï¿½bï¿½gï¿½ÌˆÊ’uï¿½ï¿½ï¿½ï¿½
                        this.gameObject.transform.position = rocketPos;//ï¿½ï¿½]ï¿½Ìï¿½ï¿½s
                        nowPosition = rocketPos;
                        /*
                        myTransform.RotateAround(PlanetPos, Vector3.up, -rotateSpeed * Time.deltaTime);//ï¿½ï¿½]ï¿½Ìï¿½ï¿½s
                        myTransform.position += planet.plaDelta;
                        */
                    }
                    else if (leftAround)
                    {
                        rotateSpeed = Mathf.Rad2Deg * ((speed + (maxCharge * chargePower)) / relativeRocketPos.magnitude);//ï¿½pï¿½ï¿½ï¿½xï¿½ÌŒvï¿½Z
                        relativeRocketPos = Quaternion.Euler(0, rotateSpeed * Time.deltaTime / Mathf.Pow(colList.Count, 2), 0) * relativeRocketPos;//ï¿½xï¿½Nï¿½gï¿½ï¿½ï¿½Ì‰ï¿½]
                        Vector3 rocketPos = relativeRocketPos + orbitCenter.transform.position;//ï¿½ï¿½ï¿½Pï¿½bï¿½gï¿½ÌˆÊ’uï¿½ï¿½ï¿½ï¿½
                        this.gameObject.transform.position = rocketPos;//ï¿½ï¿½]ï¿½Ìï¿½ï¿½s
                        nowPosition = rocketPos;
                        /*
                        myTransform.RotateAround(PlanetPos, Vector3.up, rotateSpeed * Time.deltaTime);//ï¿½ï¿½]ï¿½Ìï¿½ï¿½s
                        myTransform.position += planet.plaDelta;
                        */
                    }
                    else if (!inOrbit)
                    {
                        //ï¿½Oï¿½ï¿½ï¿½Ìê‡
                        //Debug.Log("Outside");
                        //ï¿½dï¿½Í‚ï¿½^ï¿½ï¿½ï¿½ï¿½
                        rb.AddForce(GravityForth);
                    }
                }

            }
        }
    }
    private IEnumerator antiHorizon(Vector3 horizonMove)//ï¿½ï¿½ï¿½Ú“ï¿½ï¿½Ì’ï¿½~ 
    {
        yield return new WaitForSeconds(0.35f);
        rb.velocity -= horizonMove;//ï¿½ï¿½ï¿½Ú“ï¿½ï¿½Ì’ï¿½~ï¿½Ìï¿½ï¿½s
        yield return new WaitForSeconds(0.05f);
        emergencyAvoidance = false;//ï¿½ï¿½ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½off
    }
    private void cooldown()//spï¿½ï¿½ï¿½ï¿½Nï¿½[ï¿½ï¿½ï¿½_ï¿½Eï¿½ï¿½ï¿½ï¿½ï¿½
    {
        spCooldown = false;
    }
}
